version: '3'
services:
  framework.test:
    build: .docker
    ports:
      - '80:80'
    networks:
      - framework
    volumes:
      - '.:/var/www/html'
    depends_on:
      - mariadb
  mariadb:
    image: 'mariadb:10'
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: framework
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - './.docker/dbdata:/var/lib/mysql'
    networks:
      - framework
networks:
    framework:
        driver: bridge
volumes:
    dbdata:
        driver: local
