# Schema: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
# Action docs:
  # https://github.com/actions/checkout
  # https://github.com/actions/cache

name: Composer Validation and Install

on:
  pull_request:
    branches: [ dev, staging, main ]

permissions:
  contents: read

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
